/* BU_BAMIYAN_V5_20260919 */
(function(){
  const icon=(name)=>({
    book:'<svg viewBox="0 0 24 24" aria-hidden="true"><path d="M3.5 5.5A3.5 3.5 0 0 1 7 2h4v17H7a3.5 3.5 0 0 0-3.5 3V5.5Zm17 0A3.5 3.5 0 0 0 17 2h-4v17h4a3.5 3.5 0 0 1 3.5 3V5.5Z"/></svg>',
    chart:'<svg viewBox="0 0 24 24" aria-hidden="true"><path d="M5 20V10m7 10V4m7 16v-7"/></svg>',
    cap:'<svg viewBox="0 0 24 24" aria-hidden="true"><path d="m2 9 10-5 10 5-10 5L2 9Zm4 3.2V17c3.2 2.4 8.8 2.4 12 0v-4.8"/></svg>',
    grid:'<svg viewBox="0 0 24 24" aria-hidden="true"><rect x="3" y="3" width="7" height="7" rx="1"/><rect x="14" y="3" width="7" height="7" rx="1"/><rect x="3" y="14" width="7" height="7" rx="1"/><rect x="14" y="14" width="7" height="7" rx="1"/></svg>',
    search:'<svg viewBox="0 0 24 24" aria-hidden="true"><circle cx="11" cy="11" r="7"/><path d="m20 20-4-4"/></svg>',
    home:'<svg viewBox="0 0 24 24" aria-hidden="true"><path d="m3 11 9-8 9 8v9H7v-6h10v6"/></svg>',
    news:'<svg viewBox="0 0 24 24" aria-hidden="true"><path d="M5 3h14v18H5zM8 7h8M8 11h8M8 15h5"/></svg>',
    calendar:'<svg viewBox="0 0 24 24" aria-hidden="true"><rect x="3" y="5" width="18" height="16" rx="2"/><path d="M7 2v6M17 2v6M3 10h18"/></svg>',
    user:'<svg viewBox="0 0 24 24" aria-hidden="true"><circle cx="12" cy="8" r="4"/><path d="M4 21a8 8 0 0 1 16 0"/></svg>'
  }[name]||'');
  const copies={
    fa:{kicker:'دانشگاه بهشتی | بامیان، افغانستان',title:'دانش، اخلاق، مسئولیت',desc:'آموزش و پژوهش دیجیتال با ریشه در سنت علمی اسلامی و در خدمت مردم افغانستان؛ از بامیان برای فردایی روشن‌تر.',programs:'برنامه‌های علمی',admissions:'مشاهده پذیرش',origin:'از بامیان برای افغانستان و جهان',note:'دانش برای انسان بهتر و جامعه‌ای روشن‌تر',noteEn:'A BRIGHTER HUMANITY THROUGH KNOWLEDGE',features:[['دوره‌ها و کورس‌ها','دسترسی به دوره‌های متنوع و به‌روز','/courses','grid'],['برنامه‌های تحصیلی','کارشناسی، کارشناسی ارشد و دکتری','/programs','cap'],['پژوهش','حمایت از ایده‌ها و پروژه‌های پژوهشی','/research','chart'],['کتابخانه دیجیتال','منابع علمی، مقالات و نشریات','/library','book']],search:'جستجو در دوره‌ها، استادان، مقالات و ...',searchBtn:'جستجو',courses:'دوره‌های منتخب',all:'مشاهده همه',courseItems:[['ETH101','اخلاق، هوش مصنوعی و شهروندی دیجیتال','چارچوبی برای حریم خصوصی، عدالت، شفافیت و مسئولیت در محیط دیجیتال.','/course/ethics-ai-citizenship-101'],['QNT101','استدلال کمی و سواد داده','مبانی عملی فهم داده، درصد، نرخ، آمار توصیفی و خواندن نمودارها.','/course/quantitative-reasoning-101'],['AWR101','نگارش دانشگاهی و کار با شواهد','مهارت‌های استدلال، پاراگراف دانشگاهی، بازنویسی، استناد و ویرایش.','/course/academic-writing-101']],certTitle:'نمونه مدرک دانشگاه',certSub:'نمونه‌ای حرفه‌ای از اعتبار دیجیتال و راستی‌آزمایی عمومی.',certMain:'گواهی پایان دوره',sample:'نمونه / SAMPLE',certLead:'بدین وسیله گواهی می‌شود که',name:'نام و نام خانوادگی',certCourse:'دوره «اخلاق، هوش مصنوعی و شهروندی دیجیتال» را با موفقیت به پایان رسانده است.',record:'شناسه مدرک',sign1:'معاون آموزشی',sign2:'رئیس دانشگاه',checks:['معتبر و قابل استعلام','دارای شناسه و QR','نمونه طراحی؛ بدون ادعای صدور رسمی'],verify:'بررسی اعتبار',quote:'«دانش، پلی است میان امروز ما و فردای روشن افغانستان.»',pillars:[['یادگیری','ساختاریافته'],['پژوهش','مسئولانه'],['کتابخانه','دیجیتال'],['اعتبار','قابل راستی‌آزمایی']],nav:['پروفایل','رویدادها','خانه','اخبار','بیشتر']},
    ps:{kicker:'بهشتي پوهنتون | بامیان، افغانستان',title:'پوهه، اخلاق، مسؤلیت',desc:'ډیجیټلي زده کړه او څېړنه چې په اسلامي علمي دود ولاړه ده او د افغانستان د خلکو په خدمت کې ده؛ له بامیانه تر روښانه راتلونکي.',programs:'علمي پروګرامونه',admissions:'د داخلې معلومات',origin:'له بامیانه د افغانستان او نړۍ لپاره',note:'پوهه د انسان او روښانه ټولنې لپاره',noteEn:'A BRIGHTER HUMANITY THROUGH KNOWLEDGE',features:[['کورسونه','نوې او متنوع زده کړه','/courses','grid'],['تحصیلي پروګرامونه','له لیسانس تر دوکتورا','/programs','cap'],['څېړنه','د علمي پروژو ملاتړ','/research','chart'],['ډیجیټلي کتابتون','علمي سرچینې او مقالې','/library','book']],search:'په کورسونو، استادانو او مقالو کې لټون...',searchBtn:'لټون',courses:'غوره کورسونه',all:'ټول وګورئ',courseItems:[['ETH101','اخلاق، مصنوعي ځیرکتیا او ډیجیټلي تابعیت','د مسؤل ډیجیټلي چلند عملي چوکاټ.','/course/ethics-ai-citizenship-101'],['QNT101','کمي استدلال او د معلوماتو سواد','د معلوماتو او احصایې عملي بنسټونه.','/course/quantitative-reasoning-101'],['AWR101','اکادمیکه لیکنه او شواهد','استدلال، حواله او سمون.','/course/academic-writing-101']],certTitle:'د پوهنتون د سند نمونه',certSub:'د ډیجیټلي اعتبار او عامه تایید نمونه.',certMain:'د کورس د بشپړولو سند',sample:'بېلګه / SAMPLE',certLead:'په دې وسیله تصدیق کېږي چې',name:'نوم او تخلص',certCourse:'د اخلاقو، مصنوعي ځیرکتیا او ډیجیټلي تابعیت کورس یې بشپړ کړی.',record:'د سند پېژند',sign1:'تعلیمي مرستیال',sign2:'د پوهنتون رئیس',checks:['د تایید وړ','پېژند او QR لري','د ډیزاین نمونه'],verify:'اعتبار وګورئ',quote:'«پوهه د نن او د افغانستان د روښانه سبا ترمنځ پل دی.»',pillars:[['زده کړه','منظمه'],['څېړنه','مسؤلانه'],['کتابتون','ډیجیټلي'],['اعتبار','د تایید وړ']],nav:['پروفایل','پېښې','کور','خبرونه','نور']},
    en:{kicker:'Beheshti University | Bamyan, Afghanistan',title:'Knowledge. Ethics. Responsibility.',desc:'Digital learning and research rooted in Islamic intellectual tradition and committed to serving the people of Afghanistan—from Bamyan toward a brighter future.',programs:'Academic programs',admissions:'Admissions',origin:'From Bamyan, for Afghanistan and the world',note:'Knowledge for a better human and a brighter society',noteEn:'A BRIGHTER HUMANITY THROUGH KNOWLEDGE',features:[['Courses','Current, structured learning','/courses','grid'],['Academic programs','Undergraduate to doctoral','/programs','cap'],['Research','Responsible scholarship','/research','chart'],['Digital library','Research sources and publications','/library','book']],search:'Search courses, faculty, articles...',searchBtn:'Search',courses:'Featured courses',all:'View all',courseItems:[['ETH101','Ethics, AI & Digital Citizenship','Privacy, fairness, transparency and responsible conduct.','/course/ethics-ai-citizenship-101'],['QNT101','Quantitative Reasoning & Data Literacy','Practical foundations in data and descriptive statistics.','/course/quantitative-reasoning-101'],['AWR101','Academic Writing & Evidence','Argument, citation, rewriting and evidence-based editing.','/course/academic-writing-101']],certTitle:'Sample university credential',certSub:'A professional sample of digital trust and public verification.',certMain:'Certificate of Completion',sample:'SAMPLE / نمونه',certLead:'This certifies that',name:'FULL NAME',certCourse:'has completed “Ethics, AI & Digital Citizenship”.',record:'Credential ID',sign1:'Academic Affairs',sign2:'University President',checks:['Publicly verifiable','Credential ID and QR','Design sample; not an issued credential'],verify:'Verify credential',quote:'“Knowledge is a bridge between our present and Afghanistan’s brighter future.”',pillars:[['Learning','Structured'],['Research','Responsible'],['Library','Digital'],['Credentials','Verifiable']],nav:['Profile','Events','Home','News','More']},
    fr:{kicker:'Université Beheshti | Bamyan, Afghanistan',title:'Savoir. Éthique. Responsabilité.',desc:'Un apprentissage numérique et une recherche ancrés dans la tradition intellectuelle islamique et au service de l’Afghanistan, depuis Bamyan vers un avenir meilleur.',programs:'Programmes',admissions:'Admissions',origin:'Depuis Bamyan, pour l’Afghanistan et le monde',note:'Le savoir au service de l’humain et d’une société meilleure',noteEn:'A BRIGHTER HUMANITY THROUGH KNOWLEDGE',features:[['Cours','Apprentissage structuré','/courses','grid'],['Programmes','Licence au doctorat','/programs','cap'],['Recherche','Recherche responsable','/research','chart'],['Bibliothèque','Sources et publications','/library','book']],search:'Rechercher cours, enseignants, articles...',searchBtn:'Rechercher',courses:'Cours sélectionnés',all:'Voir tout',courseItems:[['ETH101','Éthique, IA et citoyenneté numérique','Vie privée, équité, transparence et conduite responsable.','/course/ethics-ai-citizenship-101'],['QNT101','Raisonnement quantitatif et données','Fondements pratiques des données et statistiques descriptives.','/course/quantitative-reasoning-101'],['AWR101','Écriture académique et preuves','Argumentation, citation et révision fondée sur les preuves.','/course/academic-writing-101']],certTitle:'Exemple de certificat',certSub:'Un exemple professionnel de vérification numérique.',certMain:'Certificat de réussite',sample:'EXEMPLE / SAMPLE',certLead:'Il est certifié que',name:'NOM COMPLET',certCourse:'a terminé le cours « Éthique, IA et citoyenneté numérique ».',record:'Identifiant',sign1:'Affaires académiques',sign2:'Présidence',checks:['Vérifiable publiquement','Identifiant et QR','Exemple de conception'],verify:'Vérifier',quote:'« Le savoir relie notre présent à un avenir afghan plus lumineux. »',pillars:[['Apprentissage','Structuré'],['Recherche','Responsable'],['Bibliothèque','Numérique'],['Certificats','Vérifiables']],nav:['Profil','Événements','Accueil','Actualités','Plus']}
  };
  function lang(){const q=new URLSearchParams(location.search).get('lang');const d=(document.documentElement.lang||'fa').split('-')[0];return copies[q]?q:(copies[d]?d:'fa')}
  function withLang(h,l){return h+(h.includes('?')?'&':'?')+'lang='+encodeURIComponent(l)}
  function esc(s){return String(s).replace(/[&<>"]/g,m=>({'&':'&amp;','<':'&lt;','>':'&gt;','"':'&quot;'}[m]))}
  function build(){
    const main=document.querySelector('main.home-heritage'); if(!main)return;
    const mast=main.querySelector('.heritage-masthead-inner'); if(!mast)return;
    const l=lang(),c=copies[l],rtl=!['en','fr'].includes(l);
    main.setAttribute('data-bu5','ready'); document.documentElement.dir=rtl?'rtl':'ltr';
    mast.className='heritage-masthead-inner bu5-hero';
    mast.innerHTML='<div class="bu5-visual" aria-hidden="true"><div class="bu5-visual-note"><b>'+esc(c.note)+'</b><span>'+esc(c.noteEn)+'</span><i></i></div></div><div class="bu5-copy"><div class="bu5-bismillah" lang="ar" dir="rtl">بِسْمِ <em>ٱللَّٰهِ</em> ٱلرَّحْمَٰنِ ٱلرَّحِيمِ</div><div class="bu5-kicker">'+esc(c.kicker)+'</div><h1>'+esc(c.title)+'</h1><p>'+esc(c.desc)+'</p><div class="bu5-actions"><a class="primary" href="'+withLang('/programs',l)+'">'+esc(c.programs)+' <span aria-hidden="true">←</span></a><a class="ghost" href="'+withLang('/admissions',l)+'">'+esc(c.admissions)+'</a></div><div class="bu5-origin"><b>'+esc(c.origin)+'</b></div></div>';
    let shell=main.querySelector('.bu5-shell'); if(shell)shell.remove(); shell=document.createElement('div'); shell.className='bu5-shell';
    const f=c.features.map(x=>'<a class="bu5-feature" href="'+withLang(x[2],l)+'"><span class="ico">'+icon(x[3])+'</span><span><b>'+esc(x[0])+'</b><small>'+esc(x[1])+'</small></span></a>').join('');
    const courses=c.courseItems.map(x=>'<a class="bu5-course" href="'+withLang(x[3],l)+'"><div class="pic" role="img" aria-label="'+esc(x[1])+'"></div><div class="body"><span class="code">'+x[0]+'</span><h3>'+esc(x[1])+'</h3><p>'+esc(x[2])+'</p></div></a>').join('');
    const checks=c.checks.map((x,i)=>'<li><i>'+['✓','⌁','◇'][i]+'</i><span>'+esc(x)+'</span></li>').join('');
    const pillars=c.pillars.map(x=>'<div class="pillar"><b>'+esc(x[0])+'</b><span>'+esc(x[1])+'</span></div>').join('');
    shell.innerHTML='<div class="bu5-features">'+f+'</div><form class="bu5-search" role="search"><label>'+icon('search')+'<input name="q" autocomplete="off" placeholder="'+esc(c.search)+'"></label><button type="submit">'+esc(c.searchBtn)+'</button></form><div class="bu5-section-head"><h2>'+esc(c.courses)+'</h2><a href="'+withLang('/courses',l)+'">'+esc(c.all)+' ←</a></div><div class="bu5-courses">'+courses+'</div><section class="bu5-certificate"><div class="bu5-cert-paper"><div class="bu5-cert-head"><img src="/assets/beheshti-header-transparent-crop.png" alt="Beheshti University"><span>BAMIYAN · AFGHANISTAN</span></div><div class="bu5-cert-title"><h3>'+esc(c.certMain)+'</h3><span class="sample">'+esc(c.sample)+'</span><p>'+esc(c.certLead)+'</p><h4>'+esc(c.name)+'</h4><div class="course">'+esc(c.certCourse)+'</div></div><div class="bu5-cert-foot"><div class="bu5-cert-meta"><small>'+esc(c.record)+'</small><b>BU-SAMPLE-2026-0001</b></div><div class="bu5-sign"><small>'+esc(c.sign1)+'</small></div><div class="bu5-sign"><small>'+esc(c.sign2)+'</small></div><div class="bu5-seal"><div><b>BU</b><small>BAMIYAN · AFGHANISTAN</small></div></div></div></div><aside class="bu5-cert-side"><h3>'+esc(c.certTitle)+'</h3><p>'+esc(c.certSub)+'</p><ul>'+checks+'</ul><a href="'+withLang('/verify',l)+'">'+esc(c.verify)+' ←</a></aside></section><section class="bu5-band"><div class="quote">'+esc(c.quote)+'<small>BEHESHTI UNIVERSITY · BAMYAN</small></div>'+pillars+'</section>';
    mast.parentElement.insertAdjacentElement('afterend',shell);
    const sf=shell.querySelector('.bu5-search'); sf.addEventListener('submit',e=>{e.preventDefault();const q=sf.q.value.trim();location.href=withLang('/courses',l)+(q?'&q='+encodeURIComponent(q):'')});
    if(!document.querySelector('.bu5-mobile-nav')){const nav=document.createElement('nav');nav.className='bu5-mobile-nav';nav.setAttribute('aria-label','Mobile');const paths=['/profile','/events','/','/news','#'];const ics=['user','calendar','home','news','grid'];nav.innerHTML=c.nav.map((n,i)=>'<a class="'+(i===2?'active':'')+'" href="'+(i===4?'#':withLang(paths[i],l))+'">'+icon(ics[i])+'<span>'+esc(n)+'</span></a>').join('');document.body.appendChild(nav)}
  }
  let scheduled=false; function run(){if(scheduled)return;scheduled=true;requestAnimationFrame(()=>{scheduled=false;const m=document.querySelector('main.home-heritage');if(m&&m.getAttribute('data-bu5')!=='ready')build()})}
  if(document.readyState==='loading')document.addEventListener('DOMContentLoaded',run,{once:true});else run();
  new MutationObserver(run).observe(document.getElementById('app')||document.documentElement,{childList:true,subtree:true});
})();