import { db, error, json, secrets } from '@appdeploy/sdk';
import { createHash, pbkdf2Sync, randomBytes, randomInt, randomUUID, timingSafeEqual } from 'crypto';

type Account={email:string;userId:string;salt:string;passwordHash:string;iterations:number;verifiedAt:number;createdAt:number;updatedAt:number};
type Otp={email:string;userId:string;codeHash:string;challenge:string;expiresAt:number;attempts:number;createdAt:number};
type Rate={sentAt:number[];lastSentAt:number;updatedAt:number};
type Session={email:string;userId:string;name:string;expiresAt:number;createdAt:number;updatedAt:number};
export type VisitorIdentity={userId:string;email:string;name:string};
const OTP_TTL=10*60*1000,SESSION_TTL=30*24*60*60*1000,MAX_ATTEMPTS=5,PBKDF2_ITERATIONS=140000;
const str=(value:unknown)=>typeof value==='string'?value.trim():'';
const normalizeEmail=(value:unknown)=>str(value).toLowerCase();
const validEmail=(email:string)=>/^[^\s@]+@[^\s@]+\.[^\s@]+$/.test(email)&&email.length<=254;
const sha=(value:string)=>createHash('sha256').update(value).digest('hex');
export const anonymousVisitorIdentity=(value:unknown):VisitorIdentity|null=>{const visitorId=str(value);if(!/^[A-Za-z0-9._-]{16,160}$/.test(visitorId))return null;return{userId:`anon-${sha(visitorId).slice(0,32)}`,email:'',name:'مخاطب ناشناس'};};
const tableKey=(prefix:string,value:string)=>`${prefix}_${sha(value).slice(0,40)}`;
const accountTable=(email:string)=>tableKey('visitor_account_v1',email);
const rateTable=(email:string)=>tableKey('visitor_otp_rate_v1',email);
const otpTable=(challenge:string)=>tableKey('visitor_otp_v1',challenge);
const sessionTable=(token:string)=>tableKey('visitor_session_v1',token);
const first=async<T>(table:string)=>{const {items}=await db.list<T>(table,{limit:2});return items[0];};
const saveOne=async(table:string,record:Record<string,unknown>)=>{const current=await first<Record<string,unknown>>(table);if(current?.id){const [ok]=await db.update(table,[{id:current.id,record}]);return ok?current.id:null;}const [id]=await db.add(table,[record]);return id;};
const deleteOne=async(table:string)=>{const current=await first<Record<string,unknown>>(table);if(current?.id)await db.delete(table,[current.id]).catch(()=>undefined);};
const passwordHash=(password:string,salt:string,iterations:number)=>pbkdf2Sync(password,salt,iterations,32,'sha256').toString('hex');
const secureEqual=(left:string,right:string)=>{try{const a=Buffer.from(left,'hex'),b=Buffer.from(right,'hex');return a.length===b.length&&timingSafeEqual(a,b);}catch{return false;}};
const providerConfigured=async()=>{const names=await secrets.listSecretNames();return names.includes('RESEND_API_KEY')&&names.includes('SAYEH_OTP_FROM');};
const sendOtp=async(email:string,code:string)=>{const apiKey=await secrets.readSecret('RESEND_API_KEY'),from=await secrets.readSecret('SAYEH_OTP_FROM');const controller=new AbortController(),timer=setTimeout(()=>controller.abort(),10000);try{const response=await fetch('https://api.resend.com/emails',{method:'POST',headers:{Authorization:`Bearer ${apiKey}`,'Content-Type':'application/json','User-Agent':'SAYEH-NEWS/1.0','Idempotency-Key':randomUUID()},body:JSON.stringify({from,to:[email],subject:'کد تأیید ورود به SAYEH NEWS',text:`کد تأیید ورود شما به SAYEH NEWS: ${code}\nاین کد تا ۱۰ دقیقه اعتبار دارد.`,html:`<div dir='rtl' style='font-family:Arial,sans-serif;line-height:1.8'><h2>SAYEH NEWS</h2><p>کد تأیید ورود شما:</p><div style='font-size:30px;font-weight:700;letter-spacing:8px'>${code}</div><p>این کد تا ۱۰ دقیقه اعتبار دارد.</p></div>`}),signal:controller.signal});if(!response.ok)throw new Error(`email_provider_${response.status}`);}finally{clearTimeout(timer);}};
export const verifyVisitorSession=async(token:string):Promise<VisitorIdentity|null>=>{if(token.length<30)return null;const table=sessionTable(token),session=await first<Session>(table);if(!session||session.expiresAt<=Date.now()){if(session?.id)await db.delete(table,[session.id]).catch(()=>undefined);return null;}return{userId:session.userId,email:session.email,name:session.name};};
export const visitorAuthRoutes={
'GET /api/visitor-auth/status':[async()=>json({configured:await providerConfigured()})],
'POST /api/visitor-auth/anonymous':[async({body})=>{const input=(body||{}) as Record<string,unknown>,visitor=anonymousVisitorIdentity(input.visitorId);if(!visitor)return error('شناسهٔ مرورگر معتبر نیست.',400);const sessionToken=randomBytes(32).toString('base64url'),now=Date.now(),session:Session={...visitor,expiresAt:now+SESSION_TTL,createdAt:now,updatedAt:now};if(!(await saveOne(sessionTable(sessionToken),session as unknown as Record<string,unknown>)))return error('ایجاد نشست ورود انجام نشد.',500);return json({ok:true,sessionToken,visitor,expiresAt:session.expiresAt});}],
'POST /api/visitor-auth/start':[async({body})=>{const input=(body||{}) as Record<string,unknown>,email=normalizeEmail(input.email),password=typeof input.password==='string'?input.password:'';if(!validEmail(email))return error('ایمیل آدرس معتبر درج کنید.',400);if(password.length<8||password.length>128)return error('پسورد اختصاصی سایه باید حداقل ۸ کاراکتر باشد.',400);if(!(await providerConfigured()))return error('ارسال کد ایمیلی هنوز فعال نشده است.',503);const now=Date.now(),rate=await first<Rate>(rateTable(email)),recent=(rate?.sentAt||[]).filter((at)=>now-at<60*60*1000);if(rate&&now-rate.lastSentAt<60000)return error('برای ارسال دوباره کد یک دقیقه صبر کنید.',429);if(recent.length>=5)return error('تعداد درخواست کد زیاد است؛ بعداً دوباره تلاش کنید.',429);const current=await first<Account>(accountTable(email));let account:Account,newAccount=false;if(current){const digest=passwordHash(password,current.salt,current.iterations);if(!secureEqual(digest,current.passwordHash))return error('ایمیل یا پسورد اختصاصی سایه درست نیست.',401);account={email:current.email,userId:current.userId,salt:current.salt,passwordHash:current.passwordHash,iterations:current.iterations,verifiedAt:current.verifiedAt,createdAt:current.createdAt,updatedAt:now};}else{newAccount=true;const salt=randomBytes(18).toString('hex');account={email,userId:randomUUID(),salt,passwordHash:passwordHash(password,salt,PBKDF2_ITERATIONS),iterations:PBKDF2_ITERATIONS,verifiedAt:0,createdAt:now,updatedAt:now};if(!(await saveOne(accountTable(email),account as unknown as Record<string,unknown>)))return error('ایجاد حساب ورود انجام نشد.',500);}const challenge=randomBytes(24).toString('base64url'),code=String(randomInt(0,1000000)).padStart(6,'0'),otp:Otp={email,userId:account.userId,codeHash:sha(`${email}:${challenge}:${code}`),challenge,expiresAt:now+OTP_TTL,attempts:0,createdAt:now};if(!(await saveOne(otpTable(challenge),otp as unknown as Record<string,unknown>))){if(newAccount)await deleteOne(accountTable(email));return error('ایجاد کد تأیید انجام نشد.',500);}try{await sendOtp(email,code);}catch(err){await deleteOne(otpTable(challenge));if(newAccount)await deleteOne(accountTable(email));console.warn('visitor_otp_delivery_failed',{reason:err instanceof Error?err.message:'unknown'});return error('ارسال واقعی کد به ایمیل انجام نشد؛ دوباره تلاش کنید.',502);}await saveOne(rateTable(email),{sentAt:[...recent,now],lastSentAt:now,updatedAt:now});return json({ok:true,challenge,expiresInSeconds:600});}],
'POST /api/visitor-auth/verify':[async({body})=>{const input=(body||{}) as Record<string,unknown>,email=normalizeEmail(input.email),challenge=str(input.challenge),code=str(input.code).replace(/\s/g,'');if(!validEmail(email)||challenge.length<20||!/^[0-9]{6}$/.test(code))return error('کد تأیید معتبر نیست.',400);const table=otpTable(challenge),otp=await first<Otp>(table);if(!otp||otp.email!==email||otp.challenge!==challenge)return error('کد تأیید معتبر نیست.',400);if(otp.expiresAt<=Date.now()){await deleteOne(table);return error('اعتبار کد پایان یافته است؛ کد تازه بگیرید.',410);}if(otp.attempts>=MAX_ATTEMPTS){await deleteOne(table);return error('تعداد تلاش بیش از حد شد؛ کد تازه بگیرید.',429);}if(!secureEqual(sha(`${email}:${challenge}:${code}`),otp.codeHash)){await saveOne(table,{email:otp.email,userId:otp.userId,codeHash:otp.codeHash,challenge:otp.challenge,expiresAt:otp.expiresAt,attempts:otp.attempts+1,createdAt:otp.createdAt});return error('کد تأیید درست نیست.',401);}const account=await first<Account>(accountTable(email));if(!account||account.userId!==otp.userId)return error('حساب ورود یافت نشد.',404);await saveOne(accountTable(email),{email:account.email,userId:account.userId,salt:account.salt,passwordHash:account.passwordHash,iterations:account.iterations,verifiedAt:account.verifiedAt||Date.now(),createdAt:account.createdAt,updatedAt:Date.now()});await deleteOne(table);const sessionToken=randomBytes(32).toString('base64url'),now=Date.now(),visitor={userId:account.userId,email,name:email.split('@')[0]},session:Session={...visitor,expiresAt:now+SESSION_TTL,createdAt:now,updatedAt:now};if(!(await saveOne(sessionTable(sessionToken),session as unknown as Record<string,unknown>)))return error('ایجاد نشست ورود انجام نشد.',500);return json({ok:true,sessionToken,visitor,expiresAt:session.expiresAt});}],
'POST /api/visitor-auth/session':[async({body})=>{const input=(body||{}) as Record<string,unknown>,visitor=await verifyVisitorSession(str(input.sessionToken));return visitor?json({ok:true,visitor}):error('نشست ورود معتبر نیست.',401);}],
'POST /api/visitor-auth/signout':[async({body})=>{const input=(body||{}) as Record<string,unknown>,token=str(input.sessionToken);if(token)await deleteOne(sessionTable(token));return json({ok:true});}]
};